Add missing node-notifier dependency
Resolves:

$ make watch
npm run watch:examples

> uppy@0.0.1 watch:examples /Users/kvz/code/uppy
> cd website && node watch.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'node-notifier'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/kvz/code/uppy/website/watch.js:19:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node"
"/usr/local/bin/npm" "run" "watch:examples"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! uppy@0.0.1 watch:examples: `cd website && node watch.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uppy@0.0.1 watch:examples script 'cd website &&
node watch.js'.
npm ERR! This is most likely a problem with the uppy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd website && node watch.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls uppy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kvz/code/uppy/npm-debug.log
make: *** [watch] Error 1