Add autoprefixer dependency
Solves:

FATAL Something's wrong. Maybe you can find the solution here:
http://hexo.io/docs/troubleshooting.html
Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require
(/Users/kvz/code/uppy/website/node_modules/hexo/lib/hexo/index.js:213:21
)
    at
/Users/kvz/code/uppy/website/node_modules/hexo-renderer-postcss/index.js
:6:20